services:
  db:
    image: postgres:17-alpine
    container_name: fika-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: fikadb
    ports:
      - "5432:5432"
    volumes:
      - fika_postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d fikadb"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    container_name: fika-api
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/fikadb
    depends_on:
      db:
        condition: service_healthy
    restart: always
volumes:
  fika_postgres_data: